### ISSUE TITLE
Where is stored on disk the file 'devices.json' ? How to find device UUID?

### ISSUE THREAD

**Issue by dreamcat4** [svrooij/sonos-cli#1]
https://github.com/svrooij/sonos-cli/blob/d153cf0967756e0ea55bf5cf0bbb01c7311a2c1d/src/commands/zones.ts#L49

Hello,
Just trying to find my sonos device UUID since either I am not certain what it is, or it otherwise does not appear in the web interface after a firmware update anymore.

Perhaps it's gets stored here in the file `devices.json` ? However even after `strace sonos info lounge attributes 2>&1  | grep -i "device"` i still cannot find any file being opened there by that name!

Please let me know where is the:

```
const dir = this.config.dataDir.replace(/@/, '')
```

Or otherwise how to find my sonos device UUID from querying `sonos` cli program. Thank you.

**Comment by svrooij** [comment]
`sonos zones —save` to create the file. This will also display the information.
Or do `sonos zones —extended` to show all information.

**Comment by svrooij** [comment]
Didn’t you get this error?
https://github.com/svrooij/sonos-cli/blob/master/src/base.ts#L11

**Comment by dreamcat4** [comment]
Don't worry about it man. See my real problem is sonos play:1 is not being detected and probably it's due to newer firmware update. So to find the UUID... which does not seem to be explained the format of the UUID string. Even when I plug that into other program `airupnp-x86-64` it still does not work or detect anything so never mind.

**Comment by svrooij** [comment]
I experienced this before. The new Sonos speaker was already linked to some other household. You can try to reset it.

Do you have an other working speaker? Discovery works by multicast which may be blocked on your network/computer.

And you can also start from one known player by IP. `sonos zones --ip=192.168.x.x`

**Comment by dreamcat4** [comment]
This is out only speaker, which we have had from new. Never linked to any other LAN. Don't have another speaker. I can start with the `ip=` and it will query the speaker. And can see some information about it.

Really it's most likely the latest firmware. Because they have either changed API or removed features in it. And there is no known method for downgrading the firmware version back to an older firmware.

However the real issue is to use other software like `airconnect` or `airsonos` to make a bridge server for sonos to airplay. Which is what is not working here for me. I just wanted only to use your software to find the UUID to enter in the other software. Since airplay bridge server is not actually a feature of this commandline tool.

**Comment by dreamcat4** [comment]
In terms of the multicast 'not working'. Well i can see the sonos here in avahi browser. However the bonjour / mdns listing only showing up as a spotify client (`_spotify-connect._tcp` -> `sonos5CAAFD95319E`). And not also as other device types. Again, not actually certain if that is OK because there is not so much easy to find online such information as to show what the device is supposed to show and appear like.
