### ISSUE TITLE
No commands are working, other than `sonos zones`

### ISSUE THREAD

**Issue by mshulman** [svrooij/sonos-cli#15]
When I run `sonos zones`, I get back a list of my speakers:

```
% sonos zones
Searching for sonos devices... done
 Name        Zone ID                  Groupname   
 ─────────── ──────────────────────── ─────────── 
 Bathroom    RINCON_949F3E7EB53001400 Bathroom    
 Bedroom     RINCON_B8E937EFD8EC01400 Bedroom + 1 
 Bedroom     RINCON_949F3EFFCDEA01400 Bedroom + 1 
 Living Room RINCON_000E58B3858A01400 Living Room 
%
```

but when I try to get info on any of them, it fails:

```
% sonos info Bedroom volume
Sonos device discovery... done
 ›   Error: Sonos device Bedroom not found.
```

or 
```
% sonos info RINCON_B8E937EFD8EC01400 volume
Sonos device discovery... done
 ›   Error: Sonos device RINCON_B8E937EFD8EC01400 not found.
```

What should I do to debug?

**Comment by svrooij** [comment]
Can you execute `sonos zones --save` and try again?

I should really document that 🤭

According to the code `sonos info Bedroom Volume --save-zones` should also work.

Will check the CLI tomorrow.

**Comment by mshulman** [comment]
yep, that did it. I'll give you a pull request for the docs.

**Comment by mshulman** [comment]
I'm still seeing v12.18.0:

```
% sudo npm i -g @svrooij/sonos-cli
<snip>

% sonos -v
@svrooij/sonos-cli/0.1.2 darwin-x64 node-v12.18.0
```

**Comment by svrooij** [comment]
This is the version of the CLI `@svrooij/sonos-cli/0.1.2` and this is your node version `darwin-x64 node-v12.18.0`

So you now have the latest version (0.1.2) 👍
I actually created this app to have a quick way to experiment with my "new" Sonos library (at the time). And just try to easily setup a extendable CLI.

The build/release pipeline and the documentation on how it works need some work.
